// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeU15OqKXKFDru_NA3yCix_LFBisADRz8',
    appId: '1:936051104076:web:20723f7fa93f938f8757e9',
    messagingSenderId: '936051104076',
    projectId: 'elibrary-9f956',
    authDomain: 'elibrary-9f956.firebaseapp.com',
    storageBucket: 'elibrary-9f956.appspot.com',
    measurementId: 'G-PQEKCB3TYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-FX-hxQ6aNZcNXr_v7L2te205Trk1eH8',
    appId: '1:936051104076:android:5487dfb0d2ba9f6d8757e9',
    messagingSenderId: '936051104076',
    projectId: 'elibrary-9f956',
    storageBucket: 'elibrary-9f956.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjl8wJZDUqzHH6ZcXxThrT6aNSpUA80SE',
    appId: '1:936051104076:ios:aee26d4175835ff38757e9',
    messagingSenderId: '936051104076',
    projectId: 'elibrary-9f956',
    storageBucket: 'elibrary-9f956.appspot.com',
    iosClientId: '936051104076-j7tnri0tnmk8pg7cj40lps2st3t20hij.apps.googleusercontent.com',
    iosBundleId: 'com.example.elibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjl8wJZDUqzHH6ZcXxThrT6aNSpUA80SE',
    appId: '1:936051104076:ios:aee26d4175835ff38757e9',
    messagingSenderId: '936051104076',
    projectId: 'elibrary-9f956',
    storageBucket: 'elibrary-9f956.appspot.com',
    iosClientId: '936051104076-j7tnri0tnmk8pg7cj40lps2st3t20hij.apps.googleusercontent.com',
    iosBundleId: 'com.example.elibrary',
  );
}
