const book_mockdata=[{
  "book_name": "Norman",
  "image": "https://edit.org/images/cat/book-covers-big-2019101610.jpg"
}, {
  "book_name": "Nadya",
  "image": "https://edit.org/images/cat/book-covers-big-2019101610.jpg"
}, {
  "book_name": "Ellerey",
  "image": "https://edit.org/images/cat/book-covers-big-2019101610.jpg"
}, {
  "book_name": "Karlens",
  "image":"https://edit.org/images/cat/book-covers-big-2019101610.jpg"
}, {
  "book_name": "Lyn",
  "image": "https://edit.org/images/cat/book-covers-big-2019101610.jpg"
}, {
  "book_name": "Bartholomeus",
  "image": "https://edit.org/images/cat/book-covers-big-2019101610.jpg"
}, {
  "book_name": "Nerita",
  "image": "https://edit.org/images/cat/book-covers-big-2019101610.jpg"
}, {
  "book_name": "Sandor",
  "image": "https://edit.org/images/cat/book-covers-big-2019101610.jpg"
}, {
  "book_name": "Laurent",
  "image": "https://edit.org/images/cat/book-covers-big-2019101610.jpg"
}, {
  "book_name": "Neile",
  "image":"https://edit.org/images/cat/book-covers-big-2019101610.jpg"
}, {
  "book_name": "Benjamin",
  "image": "https://edit.org/images/cat/book-covers-big-2019101610.jpg"
}, {
  "book_name": "Carlota",
  "image": "https://edit.org/images/cat/book-covers-big-2019101610.jpg"
}, {
  "book_name": "Maggi",
  "image": "https://edit.org/images/cat/book-covers-big-2019101610.jpg"
}, {
  "book_name": "Conrad",
  "image": "https://edit.org/images/cat/book-covers-big-2019101610.jpg"
}, {
  "book_name": "Pall",
  "image": "https://edit.org/images/cat/book-covers-big-2019101610.jpg"
}, {
  "book_name": "Ryun",
  "image": "https://edit.org/images/cat/book-covers-big-2019101610.jpg"
}, {
  "book_name": "Antonio",
  "image": "https://edit.org/images/cat/book-covers-big-2019101610.jpg"
}, {
  "book_name": "Lulita",
  "image": "https://edit.org/images/cat/book-covers-big-2019101610.jpg"
}, {
  "book_name": "Bertrando",
  "image": "https://edit.org/images/cat/book-covers-big-2019101610.jpg"
}, {
  "book_name": "Virgil",
  "image": "https://edit.org/images/cat/book-covers-big-2019101610.jpg"
},
];